# -*- coding: utf-8 -*-
"""sistema_de_ auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFKt4tPIS5W-BNwo2zEcx2CdFn5ePsuH

# Sistema de Auditoria de Recursos Corporativos

> Thiago Rodrigues Ribeiro
"""

def calcular_orcamento()