# -*- coding: utf-8 -*-
"""sistema_de_auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ow14Qgn6xQkLPINYpsk_8EyBuSdD-Hc

# Sistema de Auditoria de Recursos Corporativos
> Thiago Rodrigues Ribeiro
"""

empresa_data = {
    "Matriz": {
        "\n TI": {
            "\n Infraestrutura": {
                "Servidores": 50000,
                "Seguranca": 30000
            },
            "\n Desenvolvimento": {
                "Frontend": 20000,
                "Backend": 25000,
                "DevOps": 15000
            }
        },
        "\n RH": {
            "\n Recrutamento": 10000,
            "Treinamento": 12000,
            "Cultura": {
                "Eventos": 5000,
                "Brindes": 2000
            }
        },
        "\n Financeiro": 40000
    }
}

import time

def auditor(calcular_orcamento):
  def wrapper(*args, **kwargs):
    print("")
    print("==== INICIANDO AUDITORIA ====")
    inicio = time.time()
    print(f"Inicio de execução :  {inicio:.4f} segundos" )
    resultado = calcular_orcamento(*args, **kwargs)
    fim = time.time()
    print(f"o tempo total em segundos: {fim - inicio:.5f}")
    print("==== FIM DA AUDITORIA ====")
    return resultado
  return wrapper

@auditor
def calcular_orcamento(empresa_data, *departamento, **calculo):

  total = 0
  for setor , valor in empresa_data.items():
    if setor in departamento:
      continue
    if isinstance(valor, dict):
        total += calcular_orcamento(valor)
    else:
        total += valor
        taxa = calculo.get("taxa_cambio")
        if taxa:
          total *= taxa
  return total

calcular_orcamento(empresa_data, "TI", taxa_cambio=4.5)
resultado = calcular_orcamento(empresa_data)
print(f"orçamento total da empresa em:  {resultado} reais")

calcular_orcamento(empresa_data)
resultado = calcular_orcamento(empresa_data)
print(f"\n orçamento total da empresa em: R$ {resultado}")