# -*- coding: utf-8 -*-
"""treino de codigo + jogo + evacuacao .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTlx_yy5rkvq9PPoSZE6mKHW_jrBMfKt
"""

# Menu para criar o usuario
print("OLÁ SEJA BEM VINDO AO SISTEMA DE EVACUAÇÃO DA UNICID")
usuario = str(input("digite o seu nome para essa simulação: "))

# definindo locais e estados dos mesmos.
locais = ["sala de aula",
          "corredor interno",
          "corredor direito",
          "corredor esquerdo",
          "escada esquerda",
          "saida"]

estados = ["Sala de aula livre",
           "corredor interno livre",
           "porta escada trancada",
           "Obstáculo escada esquerda",
           "escada esquerda livre",
           "escada direita livre",
           "saida"]

porta_chave = False
escada_esquerda_livre = False

posicao = 0
energia = 10

#Inicio da simulação
print(" \n O PRÉDIO ESTÁ SOBRE UM ALERTA DE INCÊNDIO.")
print(f"iniciando evacuação do usuário {usuario}")


while energia > 0:
  local_atual = locais[posicao]
  estado_atual = estados[posicao]


  print(f" \n Você está no {local_atual}")
  if local_atual == "corredor esquerdo" and porta_chave == True:
    print(f" estado: escada livre")
    print(f" Energia: {energia}")
  else:
    print(f" Estado: {estado_atual}")
    print(f" Energia: {energia}")

  if local_atual == "sala de aula":
    print(f"\n Devido aos alarmes soarem, o {usuario} sai da sala de aula")
    posicao += 1
    energia -= 1

  if estado_atual == "saida":
     print(f"Parabéns, {usuario} Você conseguiu sair com sucesso. ")
     break

  if estado_atual == "livre":
     posicao += 1
     energia -= 1

  #Corredor interno
  if local_atual == "corredor interno":
      print("\n estamos no corredor, podemos ir para o lado direito ou lado esquerdo.")
      resposta_usuario = str(input("digite o lado que deseja ir: ")).strip().lower()
      #criando regras para outros tipos de respostas alem das padrões
      if resposta_usuario in ["direita"]:
        resposta_usuario = "direito"
      elif resposta_usuario in ["esquerda"]:
        resposta_usuario = "esquerdo"

      if resposta_usuario not in ["direito", "esquerdo"]:
        print("Entrada Invalida. ficando no lugar")
        energia -= 1
        continue

      match resposta_usuario:
        case "esquerdo":
          print("indo para o corredor  lado esquerdo")
          posicao = 3

        case "direito":
          print("indo para o corredor  lado direito")
          posicao = 2

        case _:
            print("ERRO DE CAMINHO ")
            continue
      energia -= 1

  #Corredor esquerdo opções:

  elif local_atual == "corredor esquerdo":

    if not porta_chave:
      print("Há um obstaculo bloqueando a escada. ")
      print("1. Ir para forçar passagem pelos obstaculos")
      print("2. voltar")
      resposta_esquerda = input("digite o que deseja fazer? ").strip()
    elif resposta_esquerda:
      estado_atual = [2 + 1]
      print("\n os obstaculos da escada foram removidos. o caminho da escada está liberado")
      print(f"PARABÉNS {usuario} saiu pela escada a esquerda. ")
      posicao = 2
      break

    match resposta_esquerda:
      case "1":
        print(f"{usuario} tentou forçar a passagem pelos obstaculos, e morreu.")
        break

      case "2":
        print("Voltando para o corredor interno. ")
        if not porta_chave:
           print("\n Você encontrou uma chave voltando para o corredor interno")
        porta_chave = True
        escada_esquerda_livre = True
        print("Você ouviu um grande barulho de onde você veio. melhor se apressar.")
        posicao = 1

      case _:
        print("Não foi possivel identificar essa opção. ficando no mesmo lugar")
        continue
    energia -= 1

  # Criando o lado direito

  elif local_atual == "corredor direito":
    print(f"{usuario} está no lado direito do corredor. ")

    if not porta_chave:
      print("\n A porta para descer as escadas estão trancadas.")
      print("1. deseja procurar a chave por aqui? ")
      print("2. voltar para o corredor interno? ")
    else:
      print("\n a porta foi aberta com as chaves encontrada. ")
      print(f"PARABENS {usuario} conseguiu sair pela porta da direita")
      posicao = 5
      estado_atual = [6]
      break

    resposta_direita = input("digite o que deseja fazer? ").strip()

    match resposta_direita:
      case "1":
        print("Você procurou a chave e não encontrou em lugar nenhum.")
        print(" o Usuario teve que voltar para o corredor interno")
        posicao = 1
      case "2":
        print("Voltando para o corredor interno. ")
        posicao = 1
      case _:
        print("Não foi possivel identificar essa opção. ficando no mesmo lugar")
        continue
    energia -= 1


if energia == 0:
    print(f" Energia: {energia}")
    print(f"A Energia Acabou.  A evacuação falhou. {usuario} morreu! ")

