# -*- coding: utf-8 -*-
"""atividades do pseudocodigo parte 2 ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuIlwa8VQzE0XojPXOvkdJvuEfruaIKE
"""

# Sitema de notas de turma

def sistema_notas_turma():
        print("Quantos alunos existem na turma? ")
        total_alunos = int(input("Digite quantos alunos a turma tem: "))


        while total_alunos == 0:
            print("Não há alunos na turma")
            break

        for i in range(total_alunos):
          nome_aluno = str(input(f"\n nome do aluno:  {i+1} "))
          nota1 = float(input("Digite a primeira nota: "))
          nota2 = float(input("Digite a segunda nota: "))

          media_aluno = (nota1 + nota2) / 2

          if media_aluno >= 7.0:
           print("Aluno aprovado com media: ", media_aluno)
          elif media_aluno >= 5.0:
           print("Aluno em recuperação com media: ", media_aluno)
          else:
           print("Aluno reprovado")

sistema_notas_turma()

#Simulador de poupança

def simulador_poupanca():
  saldo = float (input("Valor inicial do investimento: "))
  taxa = float (input("taxa de juros mensal em (%):  "))
  meses = int(input("Numero de meses da simulação: "))

  for i in range(meses):
       aporte = float(input(f"\n Quanto deseja depositar no Mês  {i+1} ? "))

       saldo = saldo + aporte
       juros = aporte * (taxa/100)
       saldo = saldo + juros
       print(f"\n mes" , i + 1 , ": Saldo atualizado = R$" , saldo)

       if saldo > 200:
          print("PARABÉNS! Você atingiu a meta de 200 no mês " , i +1)
       else:
          print("meta ainda não alcançada. ")

          print("Resultado final após", i + 1 , "meses: R$" , saldo)

simulador_poupanca()