# -*- coding: utf-8 -*-
"""Atividade Treino pseudocodigos parte 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MyAKDwHm5s2M78g_9ucq50Yd6wjscHr
"""

#Função de processamento de vendas.

#Inicio do programa, declarando as varriaveis, e separando tipos de produtos.
def processar_vendas():
  total_compra = 0
  total_itens = 0
  total_final = 0

  print("Quantos produtos diferentes foram comprados?")
  itens_comprados = int(input("Quantidade de tipos: "))

  for i in range(itens_comprados):
      print("Nome do Produto: ")
      nome_produto = input("Nome: ")
      print("Preço unitário: ")
      preco_unitario = float(input("Preço: "))
      print("Quantidade deste produto:")
      quantidade = int(input("Quantidade: "))

      if    preco_unitario <= 0 or quantidade <= 0:
            print("Erro: Valores inválidos para preço ou a quantidade")
      else:
            subtotal = preco_unitario * quantidade
            total_compra = total_compra + subtotal
            itens_comprados = itens_comprados + quantidade

#aqui é o processamento do programa, onde serão aplicados as taxas de desconto.

      if total_compra >= 500.00:
        total_final = total_compra * 0.90
        print("Desconto de 10% aplicado!")
      elif total_compra >= 200.00:
        total_final = total_compra * 0.95
        print("Desconto de 5% aplicado!")
      else:
        total_final = total_compra

  print("Resumo: ", itens_comprados, "itens. Total a Pagar: R$", total_final)
  return total_final
processar_vendas()

#Analisar clima

def analisar_clima():
    soma_temperaturas: float =  0.0
    dias_quentes: int = 0
    alerta_extremo: bool =  False

# Declarando aquilo que vai aparecer para o usuário.

    for dia in range(1 , 8):
      print("\n a temperatura do dia ", dia, ": " )
      temperatura = float(input(f"Digite a temperatura do dia {dia}:"))
      soma_temperaturas = soma_temperaturas + temperatura

# Processamento dos diferentes casos e calculo de media.

      if temperatura > 35.0:
        dias_quentes = dias_quentes + 1

      elif temperatura > 45.0 or temperatura <= 5.0:
           alerta_extremo = True

      else:
            print(temperatura , ": é apenas um dia normal.")

      media = soma_temperaturas / 7
      print(f"media da temperatura na semana é de: {media:.2f}")
      print("\n dias acima de 35 ºC: ", dias_quentes )

      if alerta_extremo == True:
         print("CUIDADO: Condições climáticas perigosas detectadas! ")
      elif temperatura > 35.0:
         print("esse dia ", dia , " foi bem quente. ")
      else:
         print("Clima dentro da normalidade operacional. ")

analisar_clima ()