# -*- coding: utf-8 -*-
"""desenhando_emoji_com_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RtNxrw4etR-8PBMWkiLbhoGLVWOepi75
"""

# Estrutura base para o exercício
import matplotlib.pyplot as plt


emoji_data = {
    "nome": "Smile",
    "grade": [
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 0
        [(255,255,0), (0,0,0),     (255,255,0), (0,0,0),     (255,255,0)], # Linha 1 (Olhos)
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 2
        [(255,255,0), (0,0,0),     (0,0,0),     (0,0,0),     (255,255,0)], # Linha 3 (Boca)
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]  # Linha 4
    ]
}

#lote

for lote in range(len(emoji_data)):
  print(lote)

#linha
  for linha in range(len(emoji_data)):
    print(linha)
#pixel
    for pixel in range(len(emoji_data)):
      print(f"emoji_data{lote}{linha}{pixel}")
      if pixel == 0:
        print(pixel == 254)
      else:
        pixel == 255


plt.imshow(emoji_data["grade"])
plt.show()

# TODO: Implemente os 3 níveis de FOR aqui
# Use .items() para o dicionário e .append() para a nova lista de pixels

import matplotlib.pyplot as plt

nova_grade = []

for chave, valor in emoji_data.items():  # (lote)
    if chave == "grade":
        for linha in valor:  # (Linhas)
            nova_linha = []
            for pixel in linha:  #(Pixels)

                if pixel == (255, 255, 0):
                    # aplicar sombra (50%)
                    novo_pixel = (
                        pixel[0] // 2,
                        pixel[1] // 2,
                        pixel[2] // 2
                    )
                else:
                    novo_pixel = pixel

                nova_linha.append(novo_pixel)

            nova_grade.append(nova_linha)


emoji_data["grade"] = nova_grade


for linha in emoji_data["grade"]:
    print(linha)

plt.imshow(emoji_data["grade"])
plt.show()

biblioteca_musical = {
    "Toques": [
        {"Alegre": ([440, 480], [520, 560])},
        {"Triste": ([200, 150], [100, 50])}
    ]
}

nova_biblioteca = {"Toques": []}

for item in biblioteca_musical["Toques"]:  # nível 1 (lista)
    novo_item = {}

    for nome, matriz in item.items():  # nível 2 (dicionário)
        linha1, linha2 = matriz

        # Transposição manual (2x2)
        transposta = (
            [linha1[0], linha2[0]],
            [linha1[1], linha2[1]]
        )

        novo_item[nome] = transposta

    nova_biblioteca["Toques"].append(novo_item)

# Exibir resultado
print(nova_biblioteca)

import matplotlib.pyplot as plt

def mostrar_imagem(grade):
    plt.imshow(grade)
    plt.axis('off')  # remove eixos
    plt.show()

# pegar a imagem da sua estrutura
for item in nova_playlist["Piratas"]:
    for nome, grade in item.items():
        print(nome)
        mostrar_imagem(grade)

playlist_imagens = {
    "Piratas": [
        {
            "Pirata_5x5": [
                [(139,69,19), (139,69,19), (139,69,19), (139,69,19), (139,69,19)],  # Chapéu
                [(139,69,19), (255,255,255), (139,69,19), (0,0,0), (139,69,19)],    # Olho branco + outro olho
                [(255,224,189), (255,224,189), (255,224,189), (255,224,189), (255,224,189)],  # Rosto
                [(255,224,189), (255,224,189), (255,0,0), (255,224,189), (255,224,189)],  # Boca vermelha
                [(255,224,189), (255,224,189), (255,224,189), (255,224,189), (255,224,189)]   # Rosto
            ]
        }
    ]
}


import matplotlib.pyplot as plt
import numpy as np

for item in playlist_imagens["Piratas"]:
    for nome, grade in item.items():
        img = np.array(grade, dtype=np.uint8)

        plt.figure(figsize=(3,3))
        plt.imshow(img, interpolation='nearest')
        plt.axis('off')
        plt.title(nome)
        plt.show()