# -*- coding: utf-8 -*-
"""Codigo Auditora de vendas semanais - 1  exercicio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfuCydz6RZbXISkbZGoVTa1jIaFcF4ls
"""

# AUDITORIA DE VENDAS SEMANAIS #
# Thiago Rodrigues Ribeiro #

LIMITE_SEGURANÇA = 10000
print(LIMITE_SEGURANÇA)

venda1 = float (input("Digite o valor da 1º venda: "))
venda2 = float (input("Digite o valor da 2º venda: "))
venda3 = float (input("Digite o valor da 3º venda: "))

def analisar_vendas():
 mediavendas = (venda1 + venda2 + venda3) /3
 print("a media de vendas é: " , mediavendas)
 return mediavendas


mediavendas= analisar_vendas()
global LIMITE_SEGURANÇA
LIMITE_SEGURANÇA = int(input("\n Digite o novo limite de segurança"))

#verificando as condições.

if mediavendas > LIMITE_SEGURANÇA:
 print("\n SISTEMA EM QUARENTENA!")
elif venda1 > mediavendas * 5:
 print ("REVISAO MANUAL")
elif venda2 > mediavendas * 5:
 print ("REVISAO MANUAL")
elif venda3 > mediavendas * 5:
 print ("REVISAO MANUAL")
else:
 print ("FUNCIONAMENTO NORMAL")

#Tipos de variaveis agora

print(f"\nTipo de variavel de vendas1: " , {type(venda1)})
print(f"Tipo de variavel de vendas2: " , {type(venda2)})
print(f"Tipo de variavel de vendas3: " , {type(venda3)})
print(f"Tipo de variavel de mediavendas: " , {type(mediavendas)})
print(f"Tipo de variavel de LIMITE_SEGURANÇA: " , {type(LIMITE_SEGURANÇA)})